class Components:
    def __init__(self, obj):
        """
        See "https://smartystreets.com/docs/cloud/international-street-api#components"
        """
        self.country_iso_3 = obj.get("country_iso_3", None)
        self.super_administrative_area = obj.get("super_administrative_area", None)
        self.administrative_area = obj.get("administrative_area", None)
        self.sub_administrative_area = obj.get("sub_administrative_area", None)
        self.dependent_locality= obj.get("dependent_locality", None)
        self.dependent_locality_name = obj.get("dependent_locality_name", None)
        self.double_dependent_locality = obj.get("double_dependent_locality", None)
        self.locality = obj.get("locality", None)
        self.postal_code = obj.get("postal_code", None)
        self.postal_code_short = obj.get("postal_code_short", None)
        self.postal_code_extra = obj.get("postal_code_extra", None)
        self.premise = obj.get("premise", None)
        self.premise_extra = obj.get("premise_extra", None)
        self.premise_number = obj.get("premise_number", None)
        self.premise_type = obj.get("premise_type", None)
        self.thoroughfare = obj.get("thoroughfare", None)
        self.thoroughfare_predirection = obj.get("thoroughfare_predirection", None)
        self.thoroughfare_postdirection = obj.get("thoroughfare_postdirection", None)
        self.thoroughfare_name = obj.get("thoroughfare_name", None)
        self.thoroughfare_trailing_type = obj.get("thoroughfare_trailing_type", None)
        self.thoroughfare_type = obj.get("thoroughfare_type", None)
        self.dependent_thoroughfare = obj.get("dependent_thoroughfare", None)
        self.dependent_thoroughfare_predirection = obj.get("dependent_thoroughfare_predirection", None)
        self.dependent_thoroughfare_postdirection = obj.get("dependent_thoroughfare_postdirection", None)
        self.dependent_thoroughfare_name = obj.get("dependent_thoroughfare_name", None)
        self.dependent_thoroughfare_trailing_type = obj.get("dependent_thoroughfare_trailing_type", None)
        self.dependent_thoroughfare_type = obj.get("dependent_thoroughfare_type", None)
        self.building = obj.get("building", None)
        self.building_leading_type = obj.get("building_leading_type", None)
        self.building_name = obj.get("building_name", None)
        self.building_trailing_type = obj.get("building_trailing_type", None)
        self.sub_building_type = obj.get("sub_building_type", None)
        self.sub_building_number = obj.get("sub_building_number", None)
        self.sub_building_name = obj.get("sub_building_name", None)
        self.sub_building = obj.get("sub_building", None)
        self.post_box = obj.get("post_box", None)
        self.post_box_type = obj.get("post_box_type", None)
        self.post_box_number = obj.get("post_box_number", None)
