name: Publish Python Package

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: make test

  publish:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Package
        run: VERSION="${GITHUB_REF#refs/tags/}" make package

      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
